import { default as ChatDashboardInput } from './ChatDashboardInput/ChatDashboardInput'
import { default as ChatDashboardContent } from './ChatDashboardContent/ChatDashboardContent'
import { default as ChatDashboardHeader } from './ChatDashboardHeader/ChatDashboardHeader'
import { default as Dialogues } from './Dialogues/Dialogues'
import { default as LeftSideBar } from './LeftSideBar/LeftSideBar'
import { default as Navigation } from './Navigation/Navigation'
import { default as Profile } from './Profile/Profile'